<?php

/**
 * @file
 *  Adds some bonus features to the group module in D8.
 */

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function group_bonus_form_group_content_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  // Add an additional submit handler that will alter the redirect of the form.
  $form['actions']['submit']['#submit'][] = 'group_bonus_group_content_form_submit';
}

/**
 * Additional submit handler for group content forms that will redirect the user
 * to the content (node) page after saving it instead of the redirect to the
 * group content entity view page.
 */
function group_bonus_group_content_form_submit(array $form, \Drupal\Core\Form\FormStateInterface $form_state) {
  $entity = $form_state->getFormObject()->getEntity()->get('entity_id')->referencedEntities();
  if (!empty($entity)) {
    $entity = reset($entity);
    // Although this is easy to implement for any content type, we do it only
    // for nodes, becasue we are sure that we have a full page view for them.
    if ($entity instanceof \Drupal\node\NodeInterface) {
      $route_params = ['node' => $entity->id()];
      $form_state->setRedirect('entity.node.canonical', $route_params);
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function group_bonus_group_content_update(\Drupal\group\Entity\GroupContentInterface $entity) {
  group_bonus_invalidate_cache_for_group_content($entity);
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function group_bonus_group_content_insert(\Drupal\group\Entity\GroupContentInterface $entity) {
  group_bonus_invalidate_cache_for_group_content($entity);
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function group_bonus_group_content_delete(\Drupal\group\Entity\GroupContentInterface $entity) {
  group_bonus_invalidate_cache_for_group_content($entity);
}

/**
 * Invalidates the cache tags for the group of a group content entity.
 *
 * @param \Drupal\group\Entity\GroupContentInterface $entity
 *  The group content entity.
 */
function group_bonus_invalidate_cache_for_group_content(\Drupal\group\Entity\GroupContentInterface $entity) {
  $group = $entity->getGroup();
  \Drupal\Core\Cache\Cache::invalidateTags(array('group:' . $group->id()));
}

/**
 * Implements hook_entity_presave().
 */
function group_bonus_entity_presave(Drupal\Core\Entity\EntityInterface $entity) {
  // If the entity has the field_search_title available, then we will populate
  // it with the title of the entity (label) and append the name of the group,
  // if the entity is part of a group.
  if ($entity instanceof \Drupal\Core\Entity\FieldableEntityInterface) {
    if ($entity->hasField('field_search_title')) {
      $new_field_value = $entity->label();
      if (!$entity->isNew()) {
        $group_content = \Drupal\group\Entity\GroupContent::loadByEntity($entity);
        if (!empty($group_content)) {
          /* @var \Drupal\group\Entity\GroupContentInterface $group_content */
          $group_content = reset($group_content);
          $new_field_value .= ' ' . $group_content->getGroup()->label();
        }
      }
      $entity->set('field_search_title', $new_field_value);
    }
  }
}
